@startuml
' 2.2.3 UCs for Teacher (Lecturer)
left to right direction
skinparam packageStyle rectangle
skinparam usecase {
    BackgroundColor White
    BorderColor Black
}
skinparam actor {
    BackgroundColor White
    BorderColor Black
}

actor "Teacher (Lecturer)" as teacher

rectangle "e360 Exam Management System" {

    usecase "Login" as UC_LOGIN
    usecase "Reset Password" as UC_RESET
    usecase "Logout" as UC_LOGOUT

    usecase "View Teacher Dashboard" as UC_DASHBOARD

    usecase "View Proctor Assignments" as UC_VIEW_ASSIGN
    usecase "View Assigned Exam Details" as UC_EXAM_DETAIL

    usecase "Take Student Attendance" as UC_ATTENDANCE
    usecase "Record Student Violation" as UC_VIOLATION

    usecase "Enter Student Grades" as UC_ENTER_GRADE
    usecase "Update Student Grade" as UC_UPDATE_GRADE

}

teacher --> UC_LOGIN
teacher --> UC_LOGOUT
teacher --> UC_DASHBOARD
teacher --> UC_VIEW_ASSIGN
teacher --> UC_ATTENDANCE
teacher --> UC_VIOLATION
teacher --> UC_ENTER_GRADE
UC_LOGIN <.. UC_RESET : <<extend>>

UC_VIEW_ASSIGN <.. UC_EXAM_DETAIL : <<extend>>

UC_ATTENDANCE ..> UC_VIEW_ASSIGN : <<include>>
UC_VIOLATION ..> UC_VIEW_ASSIGN : <<include>>

UC_ENTER_GRADE <.. UC_UPDATE_GRADE : <<extend>>
UC_ENTER_GRADE ..> UC_VIEW_ASSIGN : <<include>>

@enduml
